name: TF Format
author: Esten Rye
description: Check Terraform code formatting
branding:
  icon: check-circle
  color: blue
inputs:
  working_directory:
    description: 'The directory where Terraform files are located'
    required: false
    default: '.'
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: latest
runs:
    using: 'composite'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Check Terraform formatting
        id: fmt-check
        shell: bash
        run: terraform fmt --check --recursive
        working-directory: ${{ inputs.working_directory }}
