name: TF Format
author: Esten Rye
description: Check Terraform code formatting
branding:
  icon: check-circle
  color: blue
inputs:
  working_directory:
    description: 'The directory where Terraform files are located'
    required: false
    default: '.'
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: latest
  continue_on_error:
    description: 'Whether to fail if the formatting check fails'
    required: false
    default: "false"
runs:
    using: 'composite'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Check Terraform formatting
        id: fmt-check
        shell: bash
        run: 
          terraform fmt --check --recursive
        working-directory: ${{ inputs.working_directory }}
        continue-on-error: ${{ inputs.continue_on_error }}

      # - name: Set Outputs
      #   shell: bash
      #   run: |
      #     echo "output=${{ steps.fmt-check.outputs.stdout }}" >> "$GITHUB_OUTPUT";
      #     echo "exit-code=${{ steps.fmt-check.outputs.exit-code }}" >> "$GITHUB_OUTPUT";

outputs:
  output:
    description: 'The output of the Terraform formatting check'
    value: ${{ steps.fmt-check.outputs.stdout }}
  exit-code:
    description: 'The exit code of the Terraform formatting check'
    value: ${{ steps.fmt-check.outputs.exit-code }}