name: Test Terraform Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  invalid-terraform:
    name: Validate Invalid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Invalid Terraform Formatting
        id: invalid-terraform
        uses: ./
        with:
          working_directory: './tf-tests/invalidly-formatted'
          terraform_version: 'latest'
        continue-on-error: true

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.invalid-terraform.outcome }}
          comparison: notEqual

  valid-terraform:
    name: Validate Valid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Valid Terraform Formatting
        uses: ./
        id: valid-terraform
        with:
          working_directory: './tf-tests/validly-formatted'
          terraform_version: 'latest'
          continue_on_error: true

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outcome }}
          comparison: exact
  create-release-tag:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform]
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: phish108/autotag-action@v1.1.64
        id: autotag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: create-release-tag
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-release-tag.outputs.tag }}
          release_name: ${{ needs.create-release-tag.outputs.tag }}
          body: |
            This is an automated release
          draft: false
          prerelease: false