name: Test Terraform Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  invalid-terraform:
    name: Validate Invalid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Invalid Terraform Formatting
        id: invalid-terraform
        uses: ./
        with:
          working_directory: './tf-tests/invalidly-formatted'
          terraform_version: 'latest'
        continue-on-error: true

      - name: Assert that the action failed
        uses: nick-fields/assert-action@v2
        with:
          expected: failure
          actual: ${{ steps.invalid-terraform.outcome }}
          comparison: exact

      - name: Assert that Terraform setup was successful
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.invalid-terraform.outputs.setup-terraform-outcome }}
          comparison: exact

      - name: Assert that Terraform formatting check failed
        uses: nick-fields/assert-action@v2
        with:
          expected: failure
          actual: ${{ steps.invalid-terraform.outputs.fmt-check-terraform-outcome }}
          comparison: exact

      - name: Assert that OpenTofu setup was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.invalid-terraform.outputs.setup-opentofu-outcome }}
          comparison: exact

      - name: Assert that OpenTofu formatting check was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.invalid-terraform.outputs.fmt-check-tofu-outcome }}
          comparison: exact

  invalid-opentofu:
    name: Validate Invalid OpenTofu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Invalid Terraform Formatting
        id: invalid-terraform
        uses: ./
        with:
          working_directory: './tf-tests/invalidly-formatted'
          terraform_version: 'latest'
          use_opentofu: 'true'
        continue-on-error: true

      - name: Assert that the action failed
        uses: nick-fields/assert-action@v2
        with:
          expected: failure
          actual: ${{ steps.invalid-terraform.outcome }}
          comparison: exact

      - name: Assert that Terraform setup was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.invalid-terraform.outputs.setup-terraform-outcome }}
          comparison: exact

      - name: Assert that Terraform formatting check was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.invalid-terraform.outputs.fmt-check-terraform-outcome }}
          comparison: exact

      - name: Assert that OpenTofu setup was successful
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.invalid-terraform.outputs.setup-opentofu-outcome }}
          comparison: exact

      - name: Assert that OpenTofu formatting check failed
        uses: nick-fields/assert-action@v2
        with:
          expected: failure
          actual: ${{ steps.invalid-terraform.outputs.fmt-check-tofu-outcome }}
          comparison: exact

  valid-terraform:
    name: Validate Valid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Valid Terraform Formatting
        uses: ./
        id: valid-terraform
        with:
          working_directory: './tf-tests/validly-formatted'
          terraform_version: 'latest'
          continue_on_error: true

      - name: Assert that the action succeeded
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outcome }}
          comparison: exact

      - name: Assert that Terraform setup was successful
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outputs.setup-terraform-outcome }}
          comparison: exact

      - name: Assert that Terraform formatting check succeeded
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outputs.fmt-check-terraform-outcome }}
          comparison: exact

      - name: Assert that OpenTofu setup was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.valid-terraform.outputs.setup-opentofu-outcome }}
          comparison: exact

      - name: Assert that OpenTofu formatting check was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.valid-terraform.outputs.fmt-check-tofu-outcome }}
          comparison: exact

  valid-opentofu:
    name: Validate Valid OpenTofu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Valid Terraform Formatting
        uses: ./
        id: valid-terraform
        with:
          working_directory: './tf-tests/validly-formatted'
          terraform_version: 'latest'
          continue_on_error: true
          use_opentofu: 'true'

      - name: Assert that the action succeeded
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outcome }}
          comparison: exact

      - name: Assert that Terraform setup was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.valid-terraform.outputs.setup-terraform-outcome }}
          comparison: exact

      - name: Assert that Terraform formatting check was skipped
        uses: nick-fields/assert-action@v2
        with:
          expected: skipped
          actual: ${{ steps.valid-terraform.outputs.fmt-check-terraform-outcome }}
          comparison: exact

      - name: Assert that OpenTofu setup was successful
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outputs.setup-opentofu-outcome }}
          comparison: exact

      - name: Assert that OpenTofu formatting check was successful
        uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outputs.fmt-check-tofu-outcome }}
          comparison: exact

  create-release-tag:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform, valid-opentofu, invalid-opentofu]
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GH_PAT: op://Home_Lab/GitHub-Actions-PAT/credential
      - uses: phish108/autotag-action@v1.1.64
        id: autotag
        with:
          github-token: ${{ env.GH_PAT }}
          with-v: "true"
  check-failure:
    name: Check Failure
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform, valid-opentofu, invalid-opentofu, create-release-tag]
    if: failure()
    steps:
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: op://Home_Lab/Discord-Webhooks/github-actions-bot-error
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {{ EVENT_PAYLOAD.repository.full_name }} has encountered an error.
            Github Workflow Run URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
            Github Ref : ${{github.ref}}
