name: Test Terraform Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  invalid-terraform:
    name: Validate Invalid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Invalid Terraform Formatting
        id: invalid-terraform
        uses: ./
        with:
          working_directory: './tf-tests/invalidly-formatted'
          terraform_version: 'latest'
        continue-on-error: true

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.invalid-terraform.outcome }}
          comparison: notEqual

  valid-terraform:
    name: Validate Valid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Valid Terraform Formatting
        uses: ./
        id: valid-terraform
        with:
          working_directory: './tf-tests/validly-formatted'
          terraform_version: 'latest'
          continue_on_error: true

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outcome }}
          comparison: exact
  create-pre-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Create Pre-Release
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform]
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            action.yml
            README.md
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/tags/*'
    name: Create Release
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform]
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release"
          files: |
            LICENSE.txt
            action.yml
            README.md