name: Publish Release
on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Package Contents
      run: |
        echo "Packaging contents"
        mkdir -p dist
        cp LICENSE dist/
        cp README.md dist/
        cp action.yml dist/
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{  github.ref_name }}
        workdir: dist
