name: Publish Release
on:
  workflow_run:
    workflows: [Test Terraform Action]
    types:
      - completed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create a Release
      uses: elgohr/Github-Release-Action@20240405193535
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ github.ref }}